### ISSUE TITLE
How to Build?

### ISSUE THREAD

**Issue by airbreather** [matortheeternal/xedit-lib#1]
What do I need to do to get this to build and run successfully?  Normally, I'm pretty good at this kind of stuff, but I'm not sure how to proceed here.  I got as far as running the tests, but it evidently doesn't get very far:

    XEditLib v1.0.6203.55988
    Loading Skyrim.esm (1/7)
    Exception loading Skyrim.esm
    Assertion failure (C:\Users\Joe\src\xedit-lib\lib\xedit\wbImplementation.pas, line 11710)
    Fatal Error: <EAssertionFailed: >

Running it through a debugger and continuing past that assertion, it doesn't run much longer before terminating with an access violation.  This is probably not going to come as a surprise, but I've never seen Delphi stuff before, so I'm not entirely sure where to go from here.

My kneejerk guess is that I'm running a newer version of Delphi than what you're on.

Some system details:
1. Delphi: Embarcadero® Delphi 10.1 Berlin Version 24.0.25048.9432
2. OS: Windows 10 Pro Anniversary Edition, x64 (Version 1607, OS Build 14393.447)
3. Compiled zlib with: Embarcadero C++ 7.20 for Win32

**Comment by airbreather** [comment]
Side note, I also noticed the same kind of exception when running the stuff through my little .NET app via P/Invoke... so on the plus side, if I could work through this little barrier, I might actually be able to use this.

**Comment by matortheeternal** [comment]
Hi airbreather,

It's definitely the version of Delphi you're using.  I'm happy to provide you with compiled versions of the DLL and test application if you would like.  I've been using Delphi XE.  I know that it's possible to compile xEdit with more recent Delphi versions, but some degree of modification is required (I'm fairly certain that there are branches of the main repository for this purpose).

Would compiled versions be sufficient for your needs?

**Comment by matortheeternal** [comment]
I created a pre-release with compiled versions of the DLL and executable for you.  Hope you find it useful.  Sorry for taking awhile to get back to you, I don't read my GitHub notifications as often as I should.

\- Mator

**Comment by airbreather** [comment]
Thanks!

I know from looking through the logs that you're still making major changes to both the public and private parts of this, so I didn't want to come in here asking for binaries or anything like that.  I just wanted to know how to set it up so I can see what you're seeing, and check whether or not this would be a good fit for my own automation project instead of continuing on re-implementing lots of it with my hand-rolled subset.

This mainly came about when I realized what I'd have to do to translate the high-order byte on each formId when making something like a compatibility patch, and I really wasn't looking forward to going through each type of field to find where formIds can potentially live (especially when I realized this puts VMADs in scope).  I remembered what you'd said in the first bullet point [back here](http://forum.step-project.com/topic/11514-release-stepperupper/?p=185935), and figured I'd give it a try.  Thinking about it more with what I know today, though, this is sounding more like something Smash ought to be able to do, so I'm not sure if even this is worth spending too much of my time on anymore.

**Comment by matortheeternal** [comment]
Smash doesn't have a CLI or API though, and won't for awhile still.  It also doesn't have any code for cleaning plugins (though Merge Plugins does).  You're best off using xedit-lib.  I'll be adding some functions related to finding/fixing errors soon.
