### ISSUE TITLE
Runtime error when DLL is unloaded

### ISSUE THREAD

**Issue by matortheeternal** [matortheeternal/xedit-lib#2]
When the library is unloaded it crashes and a runtime error occurs.  This is most likely due to bad finalization code.

**Comment by airbreather** [comment]
In case it helps (guessing not, but who knows?), I get what I assume is the same runtime error you're describing here, **EXCEPT** it goes away when I explicitly call [FreeLibrary](https://msdn.microsoft.com/en-us/library/ms683152.aspx) **twice**, but **only** when a Visual Studio debugger is attached.

My repro is a C# project consisting of these two C# classes: https://gist.github.com/airbreather/0146c9d13d20e44b91e7737e128c871b, plus, of course, XEditLib.dll and the Hardcoded*.dat files.

The runtime error I get looks like this:
![image](https://cloud.githubusercontent.com/assets/3792815/21644029/716b79fe-d259-11e6-9492-1215ad5db1db.png)

**Comment by matortheeternal** [comment]
Hmm.  Calling **FreeLibrary** twice sounds like very strange way of resolving the issue.  I plan on doing an more in-depth investigation when I get the chance.

**Comment by matortheeternal** [comment]
Resolved in Developer Build 358.
